# Generated by Django 4.1.5 on 2023-01-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address_Type", models.CharField(default="User", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "building_number",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "village_area",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("landmark", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module_user_id", models.IntegerField(null=True)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="create_shop_address",
                        to="user.user",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_type",
                        to="address.addresstype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_shop_address",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
