# Generated by Django 4.1.5 on 2023-01-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_alter_address_module"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="module_user_id",
            new_name="module_field_id",
        ),
    ]
