# Generated by Django 4.1.5 on 2023-01-10 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_rename_module_user_id_address_module_field_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_type",
                to="address.addresstype",
            ),
        ),
    ]
