# Generated by Django 4.1.5 on 2023-01-10 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0004_alter_address_module"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addresstype",
            old_name="address_Type",
            new_name="address_type",
        ),
        migrations.AlterField(
            model_name="address",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_module",
                to="address.addresstype",
            ),
        ),
    ]
