# Generated by Django 4.1.5 on 2023-01-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0005_rename_address_type_addresstype_address_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresstype",
            name="address_type",
            field=models.CharField(default="User Address", max_length=100),
        ),
    ]
