# Generated by Django 4.1.5 on 2023-01-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.BigIntegerField(null=True, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "created_by",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="create_user",
                        to="user.user",
                    ),
                ),
                ("role", models.ManyToManyField(to="user.role")),
                (
                    "updated_by",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_user",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
