# Generated by Django 4.1.5 on 2023-01-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_verification_alter_user_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
