# Generated by Django 4.1.5 on 2023-01-09 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        ("material_stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialstock",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material",
                to="shop.shoptype",
            ),
        ),
        migrations.DeleteModel(
            name="Material",
        ),
    ]
