# Generated by Django 4.1.5 on 2023-01-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="requester",
        ),
        migrations.AddField(
            model_name="job",
            name="requestor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_requestor",
                to="user.user",
            ),
        ),
    ]
