# Generated by Django 4.1.5 on 2023-01-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("work_experience", models.FloatField()),
                ("expected_salary", models.IntegerField()),
                ("gender", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="create_profession",
                        to="user.user",
                    ),
                ),
                (
                    "profession",
                    models.ManyToManyField(
                        db_table="work_profession",
                        related_name="professions",
                        to="job.worktype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_profession",
                        to="user.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workerdetails",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
