# Generated by Django 4.1.5 on 2023-01-10 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
        ("profession", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profession",
            name="profession",
        ),
        migrations.AddField(
            model_name="profession",
            name="profession",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_type",
                to="job.worktype",
            ),
        ),
    ]
