# Generated by Django 4.1.5 on 2023-01-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profession", "0002_remove_profession_profession_profession_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="profession",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
