version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/code
    entrypoint: ["/bin/bash", "my_civil_service_project/entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres-svc
    env_file:
      - .env

  postgres-svc:
    image: postgres
    ports:
     - "5433:5432"
    env_file:
      - .env
